apiVersion: v1
kind: Service
metadata:
  name: mynginx-svs
  labels:
    app: mynginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodeport:  30001
    protocal: TCP
selector: 
    app: mynginx
  
    
